# Travis CI Configuration File

language: php

php:
    - "5.4"

env:
    - WP_VERSION=master WP_MULTISITE=0

before_script:
    - composer install
    - echo "build.db_pass=" >> build.properties
    - vendor/bin/phing tests-init
    - cat /tmp/wordpress/wp-tests-config.php

script: pwd