# Travis CI Configuration File

language: php

php:
    - "5.4"
    - "5.5"

env:
    - WP_VERSION=master WP_MULTISITE=0

before_install: pwd

before_script:
    - composer install
    - echo "build.db_pass=" >> build.properties
    - vendor/bin/phing tests-init

script: vendor/bin/phing